version: "3.8"

services:
  jekyll:
    image: jekyll/jekyll:4.1.0
    container_name: dotnetconf-site
    environment:
      # JEKYLL_ENV=docker to fix a redirect host issue on Windows 0.0.0.0 and Docker
      # https://tonyho.net/jekyll-docker-windows-and-0-0-0-0/
      - JEKYLL_ENV=docker
    # --force_polling makes the linux box watch for any changes to files, then it will regenerate static files
    # --live reload gets the browser to automatically refresh when changes happen to files
    command: jekyll serve --force_polling --livereload
    ports:
      - 4000:4000 # port for a website
      - 35729:35729 # port for live reload
    volumes:
      - ./:/srv/jekyll
