// <auto-generated />
using BoxApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BoxApi.Migrations
{
    [DbContext(typeof(BoxDbContext))]
    [Migration("20181027103735_update1")]
    partial class update1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BoxApi.Models.Box", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<int>("Height");

                    b.Property<int>("Width");

                    b.HasKey("Id");

                    b.ToTable("Box");
                });

            modelBuilder.Entity("BoxApi.Models.Box", b =>
                {
                    b.OwnsMany("BoxApi.Models.Label", "ExtraLabels", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("BoxId")
                                .IsRequired();

                            b1.Property<string>("Color");

                            b1.Property<string>("Name");

                            b1.HasKey("Id");

                            b1.HasIndex("BoxId");

                            b1.ToTable("Box_ExtraLabels");

                            b1.HasOne("BoxApi.Models.Box")
                                .WithMany("ExtraLabels")
                                .HasForeignKey("BoxId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("BoxApi.Models.Label", "Primary", b1 =>
                        {
                            b1.Property<string>("BoxId");

                            b1.Property<string>("Color");

                            b1.Property<int>("Id");

                            b1.Property<string>("Name");

                            b1.HasKey("BoxId");

                            b1.ToTable("Box");

                            b1.HasOne("BoxApi.Models.Box")
                                .WithOne("Primary")
                                .HasForeignKey("BoxApi.Models.Label", "BoxId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("BoxApi.Models.Label", "Secondary", b1 =>
                        {
                            b1.Property<string>("BoxId");

                            b1.Property<string>("Color");

                            b1.Property<int>("Id");

                            b1.Property<string>("Name");

                            b1.HasKey("BoxId");

                            b1.ToTable("Box");

                            b1.HasOne("BoxApi.Models.Box")
                                .WithOne("Secondary")
                                .HasForeignKey("BoxApi.Models.Label", "BoxId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
